const MAX_TEMPERATURE: number = 180;
const MIN_TEMPERATURE: number = -30;

const MAX_HUMIDITY: number = 200;
const MIN_HUMIDITY: number = -180;

const MAX_PRESSURE: number = 160;
const MIN_PRESSURE: number = -120;

// WARRNING

const WARNING_MAX_TEMPERATURE: number = 120;
const WARNING_MIN_TEMPERATURE: number = -15;

export { 
    MAX_TEMPERATURE,
    MIN_TEMPERATURE,
    MAX_HUMIDITY,
    MIN_HUMIDITY,
    MAX_PRESSURE,
    MIN_PRESSURE,
    WARNING_MAX_TEMPERATURE,
    WARNING_MIN_TEMPERATURE
}