const MAX_TEMPERATURE: number = 180;
const MIN_TEMPERATURE: number = -30;

const MAX_PRESSURE: number = 160;
const MIN_PRESSURE: number = -120;

const MAX_HUMIDITY: number = 200;
const MIN_HUMIDITY: number = -180;

const WARNING_MAX_TEMPERATURE: number = 120;
const WARNING_MIN_TEMPERATURE: number = -15;

const WARNING_MAX_PRESSURE: number = 160;
const WARNING_MIN_PRESSURE: number = -120;

const WARNING_MAX_HUMIDITY: number = 120;
const WARNING_MIN_HUMIDITY: number = -90;

const INTERVAL_CALL = 1000; // Указывать в мс(1000 мс = 1с);

export { 
    MAX_TEMPERATURE,
    MIN_TEMPERATURE,
    MAX_HUMIDITY,
    MIN_HUMIDITY,
    MAX_PRESSURE,
    MIN_PRESSURE,
    WARNING_MAX_TEMPERATURE,
    WARNING_MIN_TEMPERATURE,
    WARNING_MAX_PRESSURE,
    WARNING_MIN_PRESSURE,
    WARNING_MAX_HUMIDITY,
    WARNING_MIN_HUMIDITY,
    INTERVAL_CALL
}